spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mission2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug

jwt:
  secret: likelionbackend8thmission2secretkey

file:
  dir: 'C:/Programming/LIKELION/misson/misson2/image/'